version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: 'entertainme'
    volumes:
      - mongodb_data_container:/data/db
  orchestrator:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    volumes:
      - './orchestrator:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    links:
      - mongodb
  movies:
    build:
      context: ./microservices/movies
      dockerfile: Dockerfile
    env_file:
      - ./microservices/movies/.env
    volumes:
      - './microservices/movies:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    links:
      - mongodb
  tv:
    build:
      context: ./microservices/tv
      dockerfile: Dockerfile
    env_file:
      - ./microservices/movies/.env
    volumes:
      - './microservices/tv:/usr/local/application'
      - '/usr/local/application/node_modules'
    ports:
      - '3002:3002'
    depends_on:
      - mongodb
    links:
      - mongodb

volumes:
  mongodb_data_container:
